version: "3"

services:
  influxdb:
    image: influxdb:2.0
    network_mode: host
    #    ports:
    #      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - $PWD:/local
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=louis
      - DOCKER_INFLUXDB_INIT_PASSWORD=Cyhl996l22o
      - DOCKER_INFLUXDB_INIT_ORG=ahu
      - DOCKER_INFLUXDB_INIT_BUCKET=ahu

  grafana:
    image: grafana/grafana:7.4.0
    network_mode: host
    #    ports:
    #      - "3000:3000"
    volumes:
      - grafana_plugins:/var/lib/grafana/plugins
      - grafana_data:/var/lib/grafana
      - $PWD:/local
    environment:
      GF_INSTALL_PLUGINS: 'digrich-bubblechart-panel,yesoreyeram-boomtable-panel'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_AUTH_ANONYMOUS_HIDE_VERSION: 'true'
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  influxdb_data:
  grafana_plugins:
  grafana_data:
    # driver: local
# volumes:
#   prometheus
#   grafana-plugins:
